openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /login:
    get:
      description: Returns the login page
    post:
      description: Logs in the user
  /register:
    get:
      description: Returns the register page
    post:
      description: Registers the user
  /home:
    get:
      description: Returns the home page where the sections and products are
    post:
      description: adds selected items to the cart
  /admin:
    get:
      description: Returns the admin login page
    post:
      description: Logs in the user
    /home:
      get:
        description: Returns the admin home page where the user can add sections/products
      post:
        description: Adds the sections
    /product:
      post:
        description: Adds the given product
    /cart:
      get:
        description: Returns the cart page where you can view and buy products
    /thankyou:
      get:
        description: Returns the final page after purchase
    /logout:
      get:
        description: Clears the session and logs the user out
